from __future__ import annotations

from typing import Protocol, Iterable, Optional, List
from datetime import datetime

from bot.core.models import Bar, Tick, OrderRequest, OrderResult, Position, MarketState, Signal, RiskDecision, AccountInfo


class BrokerAdapter(Protocol):
    def connect(self) -> bool: ...
    def is_connected(self) -> bool: ...
    def shutdown(self) -> None: ...

    def get_bars(self, symbol: str, timeframe: str, count: int) -> List[Bar]: ...
    def get_tick(self, symbol: str) -> Tick: ...
    def get_account_info(self) -> AccountInfo: ...
    def get_open_positions(self, symbol: Optional[str] = None) -> List[Position]: ...

    def place_order(self, order: OrderRequest) -> OrderResult: ...
    def modify_position(self, position_id: str, stop_loss: float, take_profit: float) -> OrderResult: ...
    def close_position(self, position_id: str) -> OrderResult: ...

    def symbol_info(self, symbol: str) -> dict: ...


class Strategy(Protocol):
    name: str
    def generate(
        self,
        state: MarketState,
        bars_m15: List[Bar],
        bars_h1: List[Bar],
        context: Optional[dict] = None,
    ) -> Optional[Signal]: ...


class RiskManager(Protocol):
    def approve(self, signal: Signal, state: MarketState) -> RiskDecision: ...
    def register_trade_result(self, trade: dict) -> None: ...
    def reset_daily(self, date: datetime) -> None: ...


class TradeSupervisor(Protocol):
    def evaluate(self, state: MarketState, positions: List[Position]) -> None: ...


class Reporter(Protocol):
    def daily_report(self, date: datetime) -> str: ...
